name: main

on: [push, pull_request]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, macos-latest, windows-latest ]
        php-versions: ['8.0', '8.1', '8.2']
        dependency-versions: ['lowest', 'highest']
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }} with ${{ matrix.dependency-versions }} versions of Composer dependencies
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: phpstan, phpcs, php-cs-fixer:3
        coverage: pcov

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      uses: "ramsey/composer-install@v2"
      with:
        dependency-versions: ${{ matrix.dependency-versions }}
      env:
        COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.COMPOSER_AUTH }}"}}'

    - name: Run PHP CS Fixer
      run: php-cs-fixer fix --diff --dry-run

    - name: Run PHPStan
      run: phpstan analyse src tests example

    - name: Test & Generate Code Coverage
      run: ./vendor/bin/phpunit
      env:
        PACT_LOGLEVEL: ${{ vars.PACT_LOGLEVEL }}

    - name: Upload coverage results to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        composer global require php-coveralls/php-coveralls
        php-coveralls --coverage_clover=clover.xml -v
      if: matrix.php-versions == '8.0'
